services:

  postgres-db:
    image: postgres:15-alpine
    container_name: library_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  library-web:
    image: node:22.17-alpine
    container_name: library_node_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "npm install && npx nodemon index.js"
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - .env

  migrate:
    image: migrate/migrate:v4.17.1
    volumes:
      - ./migrations:/migrations
    command: [
      "-path=/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASSWORD}@postgres-db:5432/${DB_DATABASE}?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  pgdata: